info_extracter_server/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('info_extractor/', include('info_extractor.urls')),
    path('admin/', admin.site.urls),
]

info_extractor/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings

from . import views, views_trader, views_instrument, views_portfolio, views_compare, \
    views_markets

app_name = 'info_extractor'

urlpatterns = [
    path('', views.home, name='home'),

    path('instrument/<int:instrument_id>/report/upload', views_instrument.report_upload, name='report_upload'),
    path('instrument/<int:instrument_id>/report/process', views_instrument.report_process, name='report_process'),

    path('instrument/<int:instrument_id>/stock/process', views_instrument.stock_process, name='stock_process'),

    path('instrument/list', views_instrument.instrument_list, name='instrument_list'),
    path('instrument/add', views_instrument.instrument_add, name='instrument_add'),
    path('instrument/process', views_instrument.instrument_process, name='instrument_process'),

    path('instrument/<int:instrument_id>', views_instrument.home, name='instrument'),
    path('instrument/<int:instrument_id>/reports', views_instrument.reports, name='instrument_reports'),
    path('instrument/<int:instrument_id>/report/<int:report_id>', views_instrument.report, name='instruments_report'),
    path('instrument/<int:instrument_id>/tables', views_instrument.tables, name='instrument_tables'),
    path('instrument/<int:instrument_id>/stock', views_instrument.stock_upload, name='instrument_stock'),
    path('instrument/<int:instrument_id>/analysis', views_instrument.analysis, name='instrument_analysis'),

    path('trader/list', views_trader.list, name='trader_list'),

    path('portfolio/transactions', views_portfolio.transactions, name='portfolio_transactions'),
    path('portfolio/position', views_portfolio.current_position, name='portfolio_position'),
    path('portfolio/add_transaction', views_portfolio.add_transaction, name='portfolio_add'),
    path('portfolio/process_add_transaction', views_portfolio.process_add_transaction, name='portfolio_process_add_transaction'),

    path('compare/home', views_compare.home, name='compare_home'),
    path('compare/timeperiod', views_compare.compare_time_period, name='compare_timeperiod'),
    path('compare/timeperiodresults', views_compare.compare_time_period_results, name='compare_timeperiod_results'),
    path('compare/timeseries', views_compare.compare_time_series, name='compare_timeseries'),
    path('compare/timeseriesresults', views_compare.compare_time_series_results, name='compare_timeseries_results'),

    path('market/list', views_markets.market_list, name='market_list'),
    path('market/<int:market_id>/view', views_markets.market, name='market_view'),
    path('market/<int:market_id>/upload', views_markets.upload_data_form, name='market_upload'),
    path('market/<int:market_id>/process_upload', views_markets.upload_data, name='market_upload_process'),
    path('market/add', views_markets.add_market_form, name='market_add'),
    path('market/process_add', views_markets.add_market, name='market_add_process')

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

info_extractor/models.py
import datetime

from django.db import models
from django.db.models import Max


class Market(models.Model):
    name = models.CharField(max_length=5)

    def __str__(self):
        return "Market {id: %d}" % self.id

    def convert_price(self, price, at_date, to_date):
        current_cpi = self.cpi_at(at_date)
        other_cpi = self.cpi_at(to_date)

        return price * (other_cpi / current_cpi)


    def cpi_at(self, date):
        if isinstance(date, datetime.datetime):
            date = date.date()
        cpi_query = MarketData.objects.filter(market_id=self.id, measure='CPI')

        after = cpi_query.filter(date__gte=date).order_by('date').values()
        before = cpi_query.filter(date__lte=date).order_by('-date').values()

        if len(after) == 0: # If the date is newer than all the data
            return before[0]['value']
        if len(before) == 0: # If the date is earlier than all the data
            return after[0]['value']

        after = after[0]
        before = before[0]
        after_days = (after['date'] - date).days
        before_days = (date - before['date']).days
        total_days = after_days + before_days

        if after_days == 0:
            return after['value']
        if before_days == 0:
            return before['value']

        return after['value'] * (after_days / total_days) + before['value'] * (before_days / total_days)



class MarketData(models.Model):
    market = models.ForeignKey(Market, on_delete=models.DO_NOTHING)
    measure = models.CharField(db_index=True, max_length=128)
    value = models.FloatField()
    date = models.DateField(db_index=True)

    def __str__(self):
        return "MarketData {id: %d}" % self.id


class Instrument(models.Model):
    name = models.CharField(max_length=8)
    market = models.ForeignKey(Market, on_delete=models.DO_NOTHING)

    def get_current_price(self) -> float:
        date = HistoricPrices.objects\
            .filter(instrument_id=self.id)\
            .latest('date')\
            .date

        return HistoricPrices.objects\
            .filter(date=date, instrument_id=self.id)\
            .values('close')[0]['close']

    def get_price_history(self):
        query_result = HistoricPrices.objects\
            .filter(instrument_id=self.id)\
            .values('close', 'date')

        history = {instance['date'].strftime('%Y-%m-%d'): instance['close'] for instance in query_result}

        return history

    def get_price_at(self, date) -> float:
        most_recent_date = HistoricPrices.objects \
            .filter(instrument_id=self.id, date__lte=date) \
            .aggregate(Max('date'))['date__max']

        return HistoricPrices.objects\
            .filter(date=most_recent_date, instrument_id=self.id)\
            .values('close')[0]['close']

    def __str__(self):
        return self.name + ' - ' + self.market.name

    def __hash__(self):
        return hash(self.id)

    def __eq__(self, other):
        return self.id == other.id


class ReportAnalysis(models.Model):
    instrument = models.ForeignKey(Instrument, on_delete=models.DO_NOTHING)
    year = models.IntegerField()
    polarity = models.FloatField()

    def __str__(self):
        return "Report Analysis {id: %d}" % self.id


class Transaction(models.Model):
    instrument = models.ForeignKey(Instrument, on_delete=models.DO_NOTHING)
    amount = models.FloatField()
    price = models.FloatField()
    date = models.DateTimeField()

    def __str__(self):
        return "Transaction {id: %d}" % self.id


class HistoricPrices(models.Model):
    instrument = models.ForeignKey(Instrument, on_delete=models.DO_NOTHING)
    date = models.DateField()
    open = models.FloatField()
    high = models.FloatField()
    low = models.FloatField()
    close = models.FloatField()
    adj_close = models.FloatField()
    volume = models.IntegerField()

    def __str__(self):
        return "Historic Price {id: %d}" % self.id


class Dividend(models.Model):
    instrument = models.ForeignKey(Instrument, on_delete=models.DO_NOTHING)
    date = models.DateField()
    dps = models.FloatField()

    def __str__(self):
        return "Dividend {id: %d}" % self.id

info_extractor/portfolio/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.template import loader
from django.urls import reverse

from info_extractor.models import Transaction, Instrument
from info_extractor.portfolio.lib import get_current_positions


def transactions(request):
    transaction_list = Transaction.objects.all()
    template = loader.get_template('info_extractor/portfolio/transactions.html')
    return HttpResponse(template.render({'transactions': transaction_list}, request))


def current_position(request):
    template = loader.get_template('info_extractor/portfolio/currrent_position.html')

    transaction_list = Transaction.objects.all()
    positions = get_current_positions(transaction_list)
    context = {'positions': positions}
    return HttpResponse(template.render({'positions': positions}, request))


def add_transaction(request):
    template = loader.get_template('info_extractor/portfolio/add_transaction.html')
    instruments = Instrument.objects.all()
    return HttpResponse(template.render({'instruments': instruments}, request))


def process_add_transaction(request):
    instrument = get_object_or_404(Instrument, id = request.POST.get('instrument'))
    amount = request.POST.get('amount')
    price = request.POST.get('price')
    date = request.POST.get('date')

    transaction = Transaction(
        instrument_id=instrument.id,
        amount=amount,
        price=price,
        date=date
    )
    transaction.save()

    return HttpResponseRedirect(reverse('info_extractor:portfolio_position'))

info_extractor/trader/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader


def list(request):
    template = loader.get_template('info_extractor/trader_list.html')
    return HttpResponse(template.render({}, request))

info_extractor/views.py
from django.http import HttpResponse
from django.template import loader


def home(request):
    template = loader.get_template('info_extractor/home.html')
    return HttpResponse(template.render({}, request))

info_extractor/templates/info_extractor/home.html
{% extends 'info_extractor/layout.html' %}

{% block page-header %}
Home
{% endblock %}

{% block content %}
content
{% endblock %}

info_extractor/templates/info_extractor/instrument_add.html
{% extends 'info_extractor/layout.html' %}

{% block page-header %}
Add new instrument
{% endblock %}

{% block content %}
<form action="{% url 'info_extractor:instrument_process' %}" method="post" class="form-horizontal">
    {% csrf_token %}
    <div class="form-group">
        <label for="name" class="col-md-1">Name: </label>
        <div class="col-md-3">
            <input type="text" name="name" class="form-control">
        </div>
    </div>
    <div class="form-group">
        <label for="market" class="col-md-1">Market: </label>
        <div class="col-md-3">
            <input type="text" name="market" class="form-control">
        </div>
    </div>
    <button type="submit" class="btn btn-default">Submit</button>
</form>
{% endblock %}

info_extractor/templates/info_extractor/instrument_list.html
{% extends 'info_extractor/layout.html' %}

{% block page-header %}
Instruments
{% endblock %}

{% block content %}
    <div class="list-group">
    {% for instrument in instruments %}
        <a href="{% url 'info_extractor:instrument' instrument.id %}" class="list-group-item">
            {{ instrument.name }} - {{ instrument.market }}
        </a>
    {% endfor %}
    </div>
{% endblock %}

info_extractor/templates/info_extractor/layout.html
{% load staticfiles%}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Info Extractor</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="{% static "css/styles.css" %}">

    {% block requiruments %}{% endblock %}
</head>
<body>
    <nav class="navbar navbar-default navbar-primary">
        <a class="navbar-brand" href="{% url 'info_extractor:home' %}">Info Extractor</a>
        <div class="container">
            <ul class="nav navbar-nav">
                <li><a href="{% url 'info_extractor:instrument_list' %}">Instruments</a></li>
                <li><a href="{% url 'info_extractor:trader_list' %}">Traders</a></li>
                <li><a href="{% url 'info_extractor:portfolio_position' %}">Portfolio</a></li>
                <li><a href="{% url 'info_extractor:compare_home' %}">Compare</a></li>
                <li><a href="{% url 'info_extractor:market_list' %}">Markets</a></li>
            </ul>
        </div>
    </nav>
    <nav class="navbar navbar-default navbar-secondary">
        {% block tab-bar %}{% endblock %}
    </nav>
    <div class="container">
        <div class="page-header">
            <h1>{% block page-header %}{% endblock %}</h1>
        </div>
        {% block content %}{% endblock %}
    </div>

    {% block js %}{% endblock %}
</body>
</html>

info_extractor/templates/info_extractor/trader_list.html
{% extends 'info_extractor/layout.html' %}

{% block page-header %}
  Traders
{% endblock %}

{% block content %}
  <div class="list-group">
    <a herf="#">Trader 1</a>
  </div>
{% endblock %}