info_extracter_server/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('info_extractor/', include('info_extractor.urls')),
    path('admin/', admin.site.urls),
]

info_extractor/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings

from . import views, views_trader, views_instrument, views_portfolio, views_compare, \
    views_markets

app_name = 'info_extractor'

urlpatterns = [
    path('', views.home, name='home'),

    path('instrument/<int:instrument_id>/report/upload', views_instrument.report_upload, name='report_upload'),
    path('instrument/<int:instrument_id>/report/process', views_instrument.report_process, name='report_process'),

    path('instrument/<int:instrument_id>/stock/process', views_instrument.stock_process, name='stock_process'),

    path('instrument/list', views_instrument.instrument_list, name='instrument_list'),
    path('instrument/add', views_instrument.instrument_add, name='instrument_add'),
    path('instrument/process', views_instrument.instrument_process, name='instrument_process'),

    path('instrument/<int:instrument_id>', views_instrument.home, name='instrument'),
    path('instrument/<int:instrument_id>/reports', views_instrument.reports, name='instrument_reports'),
    path('instrument/<int:instrument_id>/report/<int:report_id>', views_instrument.report, name='instruments_report'),
    path('instrument/<int:instrument_id>/tables', views_instrument.tables, name='instrument_tables'),
    path('instrument/<int:instrument_id>/stock', views_instrument.stock_upload, name='instrument_stock'),
    path('instrument/<int:instrument_id>/analysis', views_instrument.analysis, name='instrument_analysis'),

    path('trader/list', views_trader.list, name='trader_list'),

    path('portfolio/transactions', views_portfolio.transactions, name='portfolio_transactions'),
    path('portfolio/position', views_portfolio.current_position, name='portfolio_position'),
    path('portfolio/add_transaction', views_portfolio.add_transaction, name='portfolio_add'),
    path('portfolio/process_add_transaction', views_portfolio.process_add_transaction, name='portfolio_process_add_transaction'),

    path('compare/home', views_compare.home, name='compare_home'),
    path('compare/timeperiod', views_compare.compare_time_period, name='compare_timeperiod'),
    path('compare/timeperiodresults', views_compare.compare_time_period_results, name='compare_timeperiod_results'),
    path('compare/timeseries', views_compare.compare_time_series, name='compare_timeseries'),
    path('compare/timeseriesresults', views_compare.compare_time_series_results, name='compare_timeseries_results'),

    path('market/list', views_markets.market_list, name='market_list'),
    path('market/<int:market_id>/view', views_markets.market, name='market_view'),
    path('market/<int:market_id>/upload', views_markets.upload_data_form, name='market_upload'),
    path('market/<int:market_id>/process_upload', views_markets.upload_data, name='market_upload_process'),
    path('market/add', views_markets.add_market_form, name='market_add'),
    path('market/process_add', views_markets.add_market, name='market_add_process')

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

info_extractor/models.py
import datetime

from django.db import models
from django.db.models import Max


class Market(models.Model):
    name = models.CharField(max_length=5)

    def __str__(self):
        return "Market {id: %d}" % self.id

    def convert_price(self, price, at_date, to_date):
        current_cpi = self.cpi_at(at_date)
        other_cpi = self.cpi_at(to_date)

        return price * (other_cpi / current_cpi)


    def cpi_at(self, date):
        if isinstance(date, datetime.datetime):
            date = date.date()
        cpi_query = MarketData.objects.filter(market_id=self.id, measure='CPI')

        after = cpi_query.filter(date__gte=date).order_by('date').values()
        before = cpi_query.filter(date__lte=date).order_by('-date').values()

        if len(after) == 0: # If the date is newer than all the data
            return before[0]['value']
        if len(before) == 0: # If the date is earlier than all the data
            return after[0]['value']

        after = after[0]
        before = before[0]
        after_days = (after['date'] - date).days
        before_days = (date - before['date']).days
        total_days = after_days + before_days

        if after_days == 0:
            return after['value']
        if before_days == 0:
            return before['value']

        return after['value'] * (after_days / total_days) + before['value'] * (before_days / total_days)



class MarketData(models.Model):
    market = models.ForeignKey(Market, on_delete=models.DO_NOTHING)
    measure = models.CharField(db_index=True, max_length=128)
    value = models.FloatField()
    date = models.DateField(db_index=True)

    def __str__(self):
        return "MarketData {id: %d}" % self.id


class Instrument(models.Model):
    name = models.CharField(max_length=8)
    market = models.ForeignKey(Market, on_delete=models.DO_NOTHING)

    def get_current_price(self) -> float:
        date = HistoricPrices.objects\
            .filter(instrument_id=self.id)\
            .latest('date')\
            .date

        return HistoricPrices.objects\
            .filter(date=date, instrument_id=self.id)\
            .values('close')[0]['close']

    def get_price_history(self):
        query_result = HistoricPrices.objects\
            .filter(instrument_id=self.id)\
            .values('close', 'date')

        history = {instance['date'].strftime('%Y-%m-%d'): instance['close'] for instance in query_result}

        return history

    def get_price_at(self, date) -> float:
        most_recent_date = HistoricPrices.objects \
            .filter(instrument_id=self.id, date__lte=date) \
            .aggregate(Max('date'))['date__max']

        return HistoricPrices.objects\
            .filter(date=most_recent_date, instrument_id=self.id)\
            .values('close')[0]['close']

    def __str__(self):
        return self.name + ' - ' + self.market.name

    def __hash__(self):
        return hash(self.id)

    def __eq__(self, other):
        return self.id == other.id


class ReportAnalysis(models.Model):
    instrument = models.ForeignKey(Instrument, on_delete=models.DO_NOTHING)
    year = models.IntegerField()
    polarity = models.FloatField()

    def __str__(self):
        return "Report Analysis {id: %d}" % self.id


class Transaction(models.Model):
    instrument = models.ForeignKey(Instrument, on_delete=models.DO_NOTHING)
    amount = models.FloatField()
    price = models.FloatField()
    date = models.DateTimeField()

    def __str__(self):
        return "Transaction {id: %d}" % self.id


class HistoricPrices(models.Model):
    instrument = models.ForeignKey(Instrument, on_delete=models.DO_NOTHING)
    date = models.DateField()
    open = models.FloatField()
    high = models.FloatField()
    low = models.FloatField()
    close = models.FloatField()
    adj_close = models.FloatField()
    volume = models.IntegerField()

    def __str__(self):
        return "Historic Price {id: %d}" % self.id


class Dividend(models.Model):
    instrument = models.ForeignKey(Instrument, on_delete=models.DO_NOTHING)
    date = models.DateField()
    dps = models.FloatField()

    def __str__(self):
        return "Dividend {id: %d}" % self.id

info_extractor/portfolio/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.template import loader
from django.urls import reverse

from info_extractor.models import Transaction, Instrument
from info_extractor.portfolio.lib import get_current_positions


def transactions(request):
    transaction_list = Transaction.objects.all()
    template = loader.get_template('info_extractor/portfolio/transactions.html')
    return HttpResponse(template.render({'transactions': transaction_list}, request))


def current_position(request):
    template = loader.get_template('info_extractor/portfolio/currrent_position.html')

    transaction_list = Transaction.objects.all()
    positions = get_current_positions(transaction_list)
    context = {'positions': positions}
    return HttpResponse(template.render({'positions': positions}, request))


def add_transaction(request):
    template = loader.get_template('info_extractor/portfolio/add_transaction.html')
    instruments = Instrument.objects.all()
    return HttpResponse(template.render({'instruments': instruments}, request))


def process_add_transaction(request):
    instrument = get_object_or_404(Instrument, id = request.POST.get('instrument'))
    amount = request.POST.get('amount')
    price = request.POST.get('price')
    date = request.POST.get('date')

    transaction = Transaction(
        instrument_id=instrument.id,
        amount=amount,
        price=price,
        date=date
    )
    transaction.save()

    return HttpResponseRedirect(reverse('info_extractor:portfolio_position'))

info_extractor/trader/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader


def list(request):
    template = loader.get_template('info_extractor/trader_list.html')
    return HttpResponse(template.render({}, request))

info_extractor/views.py
from django.http import HttpResponse
from django.template import loader


def home(request):
    template = loader.get_template('info_extractor/home.html')
    return HttpResponse(template.render({}, request))

info_extractor/templates/info_extractor/instrument/add.html
{% extends 'info_extractor/layout.html' %}

{% block page-header %}
Add new Instrument
{% endblock %}

{% block content %}
<form action="{% url 'info_extractor:instrument_process' %}" method="post" class="form-horizontal">
    {% csrf_token %}
    <div class="form-group">
        <label for="name" class="col-md-1">Name: </label>
        <div class="col-md-3">
            <input type="text" name="name" class="form-control">
        </div>
    </div>
    <div class="form-group">
        <label for="market" class="col-md-1">Market: </label>
        <div class="col-md-3">
            <select name="market" class="form-control">
              {% for market in markets %}
                <option value="{{ market.id }}">{{ market.name }}</option>
              {% endfor %}
            </select>
        </div>
    </div>
    <button type="submit" class="btn btn-default">Submit</button>
</form>
{% endblock %}

info_extractor/templates/info_extractor/instrument/analysis.html
{% extends 'info_extractor/instrument/layout.html' %}

{% block page-header %}
    Analysis
{% endblock %}

{% block content %}
    {{ analysis|safe }}
{% endblock %}

info_extractor/templates/info_extractor/instrument/home.html
{% extends 'info_extractor/instrument/layout.html' %}

{% block requiruments %}
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
{% endblock %}

{% block page-header %}
    Overview
{% endblock %}

{% block content %}

    <div>
      <span>Dividend Yeild: </span><span>{{ div_rate|floatformat }}%</span>
      <span>Real Price Change: </span><span>{{ price_change|floatformat }}%</span>
    </div>
    <hr>

    <div class="chart-dashboard" id="stock-price-dashboard">
        <div class="chart-wrapper" id="stock-price-chart"></div>
        <div class="chart-wrapper" id="stock-price-filter"></div>
    </div>
    <div class="chart-dashboard" id="stock-volume-dashboard">
        <div class="chart-wrapper" id="stock-volume-chart"></div>
        <div class="chart-wrapper" id="stock-volume-filter"></div>
    </div>
    <div class="chart-wrapper" id="report-polarity-chart"></div>
{% endblock %}

{% block js %}
    {{ stock_price|json_script:"stock-price" }}
    {{ stock_volume|json_script:"stock-volume" }}
    {{ report_polarity|json_script:"report-polarity"}}

    <script type="text/javascript">

      let stock_price = JSON.parse($('#stock-price').text());
      let stock_volume = JSON.parse($('#stock-volume').text());
      let report_polarity = JSON.parse($('#report-polarity').text());

      for (row_idx = 1; row_idx < stock_price.length; row_idx++ ) {
        let date_components = stock_price[row_idx][0].split("-");
        stock_price[row_idx][0] = new Date(date_components[0], date_components[1], date_components[2])
      }
      for (row_idx = 1; row_idx < stock_volume.length; row_idx++ ) {
        let date_components = stock_volume[row_idx][0].split("-");
        stock_volume[row_idx][0] = new Date(date_components[0], date_components[1], date_components[2])
      }
      for (row_idx = 1; row_idx < report_polarity.length; row_idx++ ) {
        report_polarity[row_idx][0] = new Date(report_polarity[row_idx][0])
      }

      google.charts.load('current', {'packages':['corechart', 'controls']});
      google.charts.setOnLoadCallback(drawPriceChart);
      google.charts.setOnLoadCallback(drawVolumeChart);
      google.charts.setOnLoadCallback(drawPolarityChart);

      function drawPriceChart() {
        let data = google.visualization.arrayToDataTable(stock_price);

        let dashboard = new google.visualization.Dashboard($('#stock-price-dashboard')[0]);

        let dateFilter = new google.visualization.ControlWrapper({
          'controlType': 'ChartRangeFilter',
          'containerId': 'stock-price-filter',
          'options': {
            'filterColumnLabel': 'Date',
            'height': 20
          }
        });

        let chart = new google.visualization.ChartWrapper({
          'chartType': 'CandlestickChart',
          'containerId': 'stock-price-chart',
          'options': {
            'title': 'Stock Price',
            'legend': 'none'
          }
        });

        dashboard.bind(dateFilter, chart);
        dashboard.draw(data);
      }

      function drawVolumeChart() {
        let data = google.visualization.arrayToDataTable(stock_volume);

        let dashboard = new google.visualization.Dashboard($('#stock-volume-dashboard')[0]);

        let dateFilter = new google.visualization.ControlWrapper({
          'controlType': 'ChartRangeFilter',
          'containerId': 'stock-volume-filter',
          'options': {
            'filterColumnLabel': 'Date',
            'height': 50
          }
        });

        let chart = new google.visualization.ChartWrapper({
          'chartType': 'LineChart',
          'containerId': 'stock-volume-chart',
          'options': {
            'title': 'Volume Traded',
            'legend': 'right'
          }
        });

        dashboard.bind(dateFilter, chart);
        dashboard.draw(data)
      }

      function drawPolarityChart() {
        let data = google.visualization.arrayToDataTable(report_polarity);
        let options = {
          title: 'Annual Report Polarity',
          legend: { position: 'right' }
        };
        let chart = new google.visualization.LineChart($('#report-polarity-chart')[0]);
        chart.draw(data, options);
      }
    </script>
{% endblock %}

info_extractor/templates/info_extractor/instrument/layout.html
{% extends 'info_extractor/layout.html' %}

{% block tab-bar %}
    <a href="{% url 'info_extractor:instrument' instrument.id %}" class="navbar-brand">
        {{ instrument.name }} - {{ instrument.market.name }}
    </a>
    <ul class="nav navbar-nav">
        <li><a href="{% url 'info_extractor:instrument_reports' instrument.id %}">Reports</a></li>
        <li><a href="{% url 'info_extractor:instrument_tables' instrument.id %}">Tables</a></li>
        <li><a href="{% url 'info_extractor:instrument_stock' instrument.id %}">Stock</a></li>
        <li><a href="{% url 'info_extractor:instrument_analysis' instrument.id %}">Analysis</a></li>
    </ul>
{% endblock %}

info_extractor/templates/info_extractor/instrument/list.html
{% extends 'info_extractor/layout.html' %}

{% block page-header %}
Instruments
{% endblock %}

{% block content %}
    <a class="btn btn-primary" href="{% url 'info_extractor:instrument_add' %}">+</a>
    <div class="list-group">
    {% for instrument in instruments %}
        <a href="{% url 'info_extractor:instrument' instrument.id %}" class="list-group-item">
            {{ instrument.name }} - {{ instrument.market.name }}
        </a>
    {% endfor %}
    </div>
{% endblock %}

info_extractor/templates/info_extractor/instrument/report.html
{% extends 'info_extractor/instrument/layout.html' %}
{% load staticfiles%}

{% block content %}
    <div class="report-container">
        {{ report_html|safe }}
    </div>
{% endblock %}

info_extractor/templates/info_extractor/instrument/report_list.html
{% extends 'info_extractor/instrument/layout.html' %}

{% block page-header %}
    Reports
{% endblock %}

{% block content %}
    <a class="btn btn-primary" href="{% url 'info_extractor:report_upload' instrument.id %}">Upload</a>
    <div class="list-group">
        {% for report in reports %}
        <a href="{% url 'info_extractor:instruments_report' instrument.id report.id %}"
           class="list-group-item">
            {{ report.year }}
        </a>

        {% endfor %}
    </div>
{% endblock %}

info_extractor/templates/info_extractor/instrument/report_upload.html
{% extends 'info_extractor/instrument/layout.html' %}

{% block requiruments %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.4/js/bootstrap-datepicker.js"></script>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.4/css/bootstrap-datepicker.css" rel="stylesheet"/>


{% endblock %}

{% block page-header %}
Upload
{% endblock %}

{% block content %}
<form action="{% url 'info_extractor:report_process' instrument.id %}" method="post" enctype="multipart/form-data" class="form-horizontal">
    {% csrf_token %}
    <div class="form-group">
        <label for="year" class="col-md-2">Year</label>
        <div class="col-md-3">
            <input type="text" name="year" id="datepicker" class="form-control">
        </div>
    </div>
    <div class="form-group">
        <label for="report" class="col-md-2">Anual Report</label>
        <div class="col-md-3">
            <input type="file" name="report" class="form-control">
        </div>
    </div>
    <button type="submit" class="btn btn-default">Save</button>
</form>
{% endblock %}

{% block js %}
    <script>
        $("#datepicker").datepicker({
            format: "yyyy",
            viewMode: "years",
            minViewMode: "years"
        }).on('changeDate', function(e){
            $(this).datepicker('hide');
        });
    </script>
{% endblock %}

info_extractor/templates/info_extractor/instrument/stock_upload.html
{% extends 'info_extractor/instrument/layout.html' %}

{% block page-header %}
Upload Stock data
{% endblock %}

{% block content %}
<form action="{% url 'info_extractor:stock_process' instrument.id %}" method="post" enctype="multipart/form-data" class="form-horizontal">
    {% csrf_token %}
    <div class="form-group">
        <label for="stock_file" class="col-md-2">Stock price data</label>
        <div class="col-md-3">
            <input type="file" name="stock_file" class="form-control">
        </div>
    </div>
    <div class="form-group">
      <label for="div_file" class="col-md-2">Stock Dividend data</label>
      <div class="col-md-3">
        <input type="file" name="div_file" class="form-control">
      </div>
    </div>
    <button type="submit" class="btn btn-default">Save</button>
</form>
{% endblock %}

info_extractor/templates/info_extractor/instrument/tables.html
{% extends 'info_extractor/instrument/layout.html' %}

{% block page-header %}
  Tables
{% endblock %}

{% block content %}
  {% for report_tables in tables %}
    <h2>{{ report_tables.year }}</h2>

    <div class="tables-container">
      {{ report_tables.html|safe }}
    </div>
  {% endfor %}
{% endblock %}